
---
name: Thadryan
surname: Sweeney
position: "Technologist, Instructor"
phone: +978 696 6946
www: "sweeney-th.github.io"
email: "thadryan@protonmail.com"
twitter: ThadryanJS
github: sweeney-th
linkedin: "thadryan-sweeney-10b938a"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

I am a Computational Biologist and Scientific Software Developer interested in applying statistical and computational techniques to the study of systems large and small.

# Research Positions

```{r}

tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Research Technologist", "2020", "Mass General/Harvard Medical School", "Boston, MA",
  "Bioinformatics & Data Science Contractor", "2018", "bluebird bio", "Cambridge, MA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Education

```{r}

tribble(
  ~Degree, ~Year, ~Institution, ~Where,
  "Associate of Arts",   "2011", "Greenfield Community College",   "Greenfield, MA",
  "Bachelor of Science", "2013", "American International College", "Springfield, MA",
  "Master of Science",   "2019", "Northeastern University",        "Boston, MA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Teaching

```{r}

tribble(
  ~Year, ~Class, ~ Where,
  2020, "Bioinformatics Methods I (spring)", "Northeastern University",
  2020, "Bioinformatics Methods I (fall)", "Northeastern University",
  2021, "Bioinformatics Methods I (spring)", "Northeastern University"  
) %>% 
  detailed_entries(Class, Year, Where)
```

# Published Software

```{r}
tribble(
  ~Year, ~Type, ~Desc, 
  2020, "An interactive Bayesian Ttool for SARS-CoV2-Antibody test interpretation", "Manuscript supplement, https://covid.omics.kitchen/",
  2020, "ContrApption: interactive visualization of RNA-Seq style datasets from a single function call", "(beta) https://github.com/omics-kitchen/ContrApption",
) %>% 
  brief_entries(glue::glue("{Type}"), Year, Desc)
```

# Publications

## Published

```{R}

tribble(
  ~Year, ~Desc, ~Note,
  "2021", "Evaluation of serological lateral flow assays for severe acute respiratory syndrome coronavirus-2",
    "Supplement: https://covid.omics.kitchen/"
) %>%
  detailed_entries(Desc, glue::glue("{Year}"), Note)
```

## In Revision

```{R}

tribble(
  ~Year, ~Desc, ~Note,
  "2021", "Distinct stress-dependent signatures of cellular and extracellular tRNA-derived small RNAs (tDRs)", "https://www.biorxiv.org/content/10.1101/2021.09.03.458085v1",
  "2021", "An Examination of Small RNA Expression in Multiple Tissues and Their Detection in Biofluids", "",
) %>%
  detailed_entries(Desc, glue::glue("{Year}"), Note)
```

## Submitted

```{R}

tribble(
  ~Year, ~Desc, ~Note,
  "TBD", "Elevation of Neuronal Injury Markers in Patients with Neurologic Sequelae after Hospitalization for SARS-CoV-2 Infection", ""
) %>%
  detailed_entries(Desc, glue::glue("{Year}"), Note)
```

## In preparation

```{R}

tribble(
  ~Year, ~Desc, ~Note,
  "TBD", "miRNAs in canine mitral value disorders", "",
  "TBD", "Increased levels of the synaptic proteins PSD-95, SNAP-25, and Neurogranin in the cerebrospinal fluid of patients with Alzheimer’s Disease", "",
  "TBD", "ContrApption: interactive visualization of RNA-Seq style datasets from a single function call","",
) %>%
  detailed_entries(Desc, glue::glue("{Year}"), Note)
```

# Media

```{r}

tribble(
  ~Year, ~Desc, ~Note,
  2020, "COVID-19 LFA Research", "https://www.wcvb.com/article/boston-researchers-assess-performance-of-covid-19-antibody-tests/33625088"
) %>% 
  brief_entries(Desc, Year, Note)
```